### PR TITLE
Use make_travis_yml generated .travis.yml

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by bergmark** [comment]
Ouch, actual test suite failures.

**Comment by phadej** [comment]
Pushed another commit to build tests with 8.0.1.

Cannot help with test failures though :(

**Comment by bergmark** [comment]
Probably something gone wrong when upgrading template-haskell for some other ghc release.

**Comment by phadej** [comment]
Ok, GHC 8.0.1 compiles, but doesn't work :) I hope you can continue from here.

**Comment by bergmark** [comment]
This is a good start at least, thank you!

**Pull request merged**
